name: mosallas
description: mosallas online shop

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: 0.22.0
  http: 0.13.3
  package_info: 2.0.2
  mask_text_input_formatter: ^2.0.0
  provider: 5.0.0
  share: 2.0.1
  shared_preferences: 2.0.5
  connectivity: 3.0.6
  sliding_up_panel: ^2.0.0+1
  persian_number_utility: 0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/

  fonts:
    - family: Farnaz
      fonts:
        - asset: assets/font/Farnaz.ttf
    - family: Koodak
      fonts:
        - asset: assets/font/Farnaz.ttf
    - family: DanaRegular
      fonts:
        - asset: assets/font/DanaRegular.ttf
    - family: DanaBold
      fonts:
        - asset: assets/font/DanaBold.ttf
    - family: DanaLight
      fonts:
        - asset: assets/font/DanaLight.ttf
    - family: DanaMedium
      fonts:
        - asset: assets/font/DanaMedium.ttf
    - family: DanaFaNumMedium
      fonts:
        - asset: assets/font/DanaFaNumMedium.ttf
